### ISSUE TITLE
References with Author Year style

### ISSUE THREAD

**Issue by d70-t** [eurec4a/how_to_eurec4a#55]
References should be in Author Year style in stead of initial letter. However we are not yet sure how to set this up properly. See #54 for the progress so far.

**Comment by observingClouds** [comment]
I follow up on this issue because not only does the *author year* look more pleasing, but it makes more sense when differentiating between text-citations and parentheses-citations. I think the readability of the pages would benefit from this distinction.

#75 applies this distinction and also changes to the *author year* format.

What is your opinion? This requires `sphinxcontrib.bibtex>=2.2.0` but shouldn't be any longer of concern as it was in #54 and in particular in [this comment](https://github.com/eurec4a/how_to_eurec4a/pull/54#pullrequestreview-649805677). Version 2.2.0 is over a year old and should be widely supported by now.

**Comment by observingClouds** [comment]
Thanks for the positive feedback!

I cannot follow from the your @d70-t referenced commit that we need to bump up the `jupyterbook` version. The referenced commit is already present in version [0.11.0a1](https://github.com/executablebooks/jupyter-book/tree/abb74c01070542377c3256a7118d4e47f21b0898). Therefore the current requirement of `jupyter-book>0.11.0` should be fine, right?

**Comment by d70-t** [comment]
Indeed... it seems I'm not skillful enough in using `git blame` properly...

**Comment by observingClouds** [comment]
Great, then #75 should now close this issue 😄

**Comment by d70-t** [comment]
#75 is now merged 🎉
